### PR TITLE
Live reload per-host clients

### LINKED ISSUE #218: Per host clients should be live reloaded
## What happened?

We currently create new per-host clients every time service configuration updates. This means that logic that's actively using a client for a still-existing host will be out of date without explicit intervention which is unexpected and a bit hard to work around.

## What did you want to happen?

We should preserve clients for hosts that still exist across refreshes.

### PR DESCRIPTION
**Pull request by sfackler**
## Before this PR
Each client in a per-host-clients context was static - its internal configuration would not live reload based on config changes even when that host was still present. This makes it hard to use in some contexts where there are background tasks happening on a per-host basis.

## After this PR

==COMMIT_MSG==
Each per-host client now live reloads as long as that host remains in the service configuration.
==COMMIT_MSG==

Closes #218

### CODE REVIEW

File: conjure-runtime/src/client_factory.rs [hunk 1]
```diff
@@ -401,28 +414,66 @@ impl ClientFactory {
...
+                        new_client_handles.insert(host, client_handle);
                     }
 
-                    Ok(PerHostClients { clients })
+                    client_handles = new_client_handles;
+                    match errors.pop() {
+                        Some(e) => {
+                            for e2 in errors {
+                                warn!("error reloading per-host clients", error: e2);
+                            }
```
Comment (sfackler) [inline conjure-runtime/src/client_factory.rs:462]: The error handling here is all deferred so we don't lose track of state when a subset of clients have issues updating. I don't expect that to be a common case but wanted to make sure we handled it.

File: conjure-runtime/src/client_factory.rs [hunk 2]
```diff
@@ -301,16 +303,27 @@ impl ClientFactory {
...
+    }
 
-        let state = state_builder.build(&service_config.get(), None)?;
+    fn raw_client<T>(
+        state_builder: T,
+        service_config: Refreshable<ServiceConfig, Error>,
+        override_host_index: Option<usize>,
+    ) -> Result<Client, Error>
+    where
+        T: Borrow<StateBuilder> + 'static + Sync + Send,
```
Comment (pierceforte) [inline conjure-runtime/src/client_factory.rs:316]: I'm trying to understand how this `Borrow` type works (and why it's useful vs. just using `&T`).

I read about it here https://doc.rust-lang.org/std/borrow/trait.Borrow.html. Is it sort of like `String`, in that you can just pass `T` directly, but it can be implicitly cast to `&T` (or `&str`) because it implements `Borrow`?

File: conjure-runtime/src/client_factory.rs [hunk 3]
```diff
@@ -401,28 +414,66 @@ impl ClientFactory {
...
+                                ClientHandle { client, handle }
+                            }
+                        };
+
+                        clients.insert(host.clone(), make_client(client_handle.client.clone()));
+                        new_client_handles.insert(host, client_handle);
                     }
 
-                    Ok(PerHostClients { clients })
+                    client_handles = new_client_handles;
```
Comment (pierceforte) [inline conjure-runtime/src/client_factory.rs:457]: Where is `client_handles` used?

File: conjure-runtime/src/client_factory.rs [hunk 4]
```diff
@@ -301,16 +303,27 @@ impl ClientFactory {
...
-
         let state_builder = self.state_builder(service);
+        Self::raw_client(state_builder, service_config, None)
+    }
 
-        let state = state_builder.build(&service_config.get(), None)?;
+    fn raw_client<T>(
+        state_builder: T,
+        service_config: Refreshable<ServiceConfig, Error>,
+        override_host_index: Option<usize>,
```
Comment (pierceforte) [inline conjure-runtime/src/client_factory.rs:313]: I see this is part of the `CachedConfig` type. It says it `Overrides the `hostIndex` field included in metrics.` What is the purpose of that?

File: conjure-runtime/src/client_factory.rs (hunk 1 above)
Comment (pierceforte) [reply conjure-runtime/src/client_factory.rs:462]: Where are we updating the state in this method? As in, what would be lost if we returned the error early here https://github.com/palantir/conjure-rust-runtime/pull/219/files#diff-6d2572eabc17f7b3329877aef40ce0daeebbc8cb310e2c5394e530c28b6d42f4R446?

File: conjure-runtime/src/client_factory.rs (hunk 3 above)
Comment (sfackler) [reply conjure-runtime/src/client_factory.rs:457]: It's used up on line 429.

File: conjure-runtime/src/client_factory.rs (hunk 1 above)
Comment (sfackler) [reply conjure-runtime/src/client_factory.rs:462]: We'd forget about some of the clients so the next refresh we'd end up making new ones for those hosts instead of reloading the old ones.

File: conjure-runtime/src/client_factory.rs (hunk 2 above)
Comment (sfackler) [reply conjure-runtime/src/client_factory.rs:316]: It has some extra requirements that are used in some other places, but the key thing in this context is that it's a trait implemented by both `T` and `Arc<T>` that lets you get a `&T`. This function is called in 2 places. The per-host stuff needs to store the state builder in an arc, while the normal stuff up in client_inner doesn't and this bound makes both work.

File: conjure-runtime/src/client_factory.rs (hunk 4 above)
Comment (sfackler) [reply conjure-runtime/src/client_factory.rs:313]: There are some metrics which are tracked for each URI separately with a `hostIndex` field. Normally that's determined by the index of the URI in the URIs list of the ServiceConfig, but the per-host logic ends up making a separate ServiceConfig for each URI. Without the override each of those would end up using hostIndex 0 so the metrics would all get merged.

File: conjure-runtime/src/client_factory.rs (hunk 3 above)
Comment (pierceforte) [reply conjure-runtime/src/client_factory.rs:457]: I think where I'm confused is this (line 457) is outside of the loop. So how does our reassignment here affect line 429?

Comment (sfackler) [reply conjure-runtime/src/client_factory.rs:457]: Oh yeah, it's not updating it for the next loop iteration, it's updating it for the next call to this closure (i.e. the next time the service config changes)

**Review by pierceforte — APPROVED** [review]
